- hosts: web
  tasks:
    - name: Install IIS
      win_dsc:
        resource_name: WindowsFeature
        Ensure: Present
        Name: Web-Server
      register: iis

    - name: Remove Default Site
      win_dsc:
        resource_name: xWebsite
        Ensure: Absent
        Name: Default Web Site
      when: iis.dsc_attributes.Ensure == 'Present'

    - name: New Site
      win_dsc:
        resource_name: xWebsite
        Name: MyWebSite
        State: Started
        PhysicalPath: C:\example.com
        BindingInfo:
          - Protocol: http
            Port: 80
      when: iis.dsc_attributes.Ensure == 'Present'
